version: "3.8"

services:
  postgres:
    image: postgres:15.10-alpine
    command: [postgres, --max_connections=100]
    environment:
      - POSTGRES_PASSWORD=[sua senha]
    ports:
      - "5432:5432"
    networks:
      - postgres-network
      - traefik-public
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    restart: always  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 

  pgadmin:
    image: dpage/pgadmin4:6.15
    environment:
      PGADMIN_DEFAULT_EMAIL: [seu emai]
      PGADMIN_DEFAULT_PASSWORD: [sua senha]
    ports:
      - "5050:80"
    networks:
      - postgres-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.service=pgadmin"
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.seudominio.com.br`)"
        - "traefik.http.routers.pgadmin.entrypoints=websecure"
        - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80" 
        - "traefic.http.routers.pgadmin.tls=true"
volumes:
  postgres_data:
    external: true

networks:
  postgres-network:
    external: true 
  traefik-public:
    external: true